target:
- readmission_30d
continuous_cols:
- subject_id
- hadm_id
- hospital_expire_flag
- anchor_age
- icd_version
- stay_id
- los
- mean_Anion Gap
- mean_Bicarbonate
- mean_Calcium, Total
- mean_Chloride
- mean_Creatinine
- mean_Glucose
- mean_Hematocrit
- mean_Hemoglobin
- mean_MCH
- mean_MCHC
- mean_MCV
- mean_Magnesium
- mean_Phosphate
- mean_Platelet Count
- mean_Potassium
- mean_RDW
- mean_Red Blood Cells
- mean_Sodium
- mean_Urea Nitrogen
- mean_White Blood Cells
- min_Anion Gap
- min_Bicarbonate
- min_Calcium, Total
- min_Chloride
- min_Creatinine
- min_Glucose
- min_Hematocrit
- min_Hemoglobin
- min_MCH
- min_MCHC
- min_MCV
- min_Magnesium
- min_Phosphate
- min_Platelet Count
- min_Potassium
- min_RDW
- min_Red Blood Cells
- min_Sodium
- min_Urea Nitrogen
- min_White Blood Cells
- max_Anion Gap
- max_Bicarbonate
- max_Calcium, Total
- max_Chloride
- max_Creatinine
- max_Glucose
- max_Hematocrit
- max_Hemoglobin
- max_MCH
- max_MCHC
- max_MCV
- max_Magnesium
- max_Phosphate
- max_Platelet Count
- max_Potassium
- max_RDW
- max_Red Blood Cells
- max_Sodium
- max_Urea Nitrogen
- max_White Blood Cells
- admitted_to_icu
- hospital_los
- gender_F
- gender_M
categorical_cols:
- race_encoded
- icd_code_encoded
date_columns: []
encode_date_columns: true
validation_split: 0.2
continuous_feature_transform: null
normalize_continuous_features: true
quantile_noise: 0
num_workers: 0
pin_memory: true
handle_unknown_categories: true
handle_missing_values: true
dataloader_kwargs: {}
task: classification
head: LinearHead
head_config:
  layers: ''
embedding_dims:
- - 34
  - 17
- - 20655
  - 50
embedding_dropout: 0.0
batch_norm_continuous_input: true
learning_rate: 0.001
loss: CrossEntropyLoss
metrics:
- auroc
metrics_prob_input:
- false
metrics_params:
- sub_params_list:
  - task: multiclass
    num_classes: 2
target_range: null
virtual_batch_size: null
seed: 42
_module_src: models.tab_transformer
_model_name: TabTransformerModel
_backbone_name: TabTransformerBackbone
_config_name: TabTransformerConfig
input_embed_dim: 32
embedding_initialization: kaiming_uniform
embedding_bias: false
share_embedding: false
share_embedding_strategy: fraction
shared_embedding_fraction: 0.25
num_heads: 8
num_attn_blocks: 6
transformer_head_dim: null
attn_dropout: 0.1
add_norm_dropout: 0.1
ff_dropout: 0.1
ff_hidden_multiplier: 4
transformer_activation: GEGLU
batch_size: 1024
data_aware_init_batch_size: 2000
fast_dev_run: false
max_epochs: 10
min_epochs: 1
max_time: null
accelerator: cpu
devices: -1
devices_list: null
accumulate_grad_batches: 1
auto_lr_find: false
auto_select_gpus: true
check_val_every_n_epoch: 1
gradient_clip_val: 0.0
overfit_batches: 0.0
deterministic: false
profiler: null
early_stopping: valid_loss
early_stopping_min_delta: 0.001
early_stopping_mode: min
early_stopping_patience: 3
early_stopping_kwargs: {}
checkpoints: valid_loss
checkpoints_path: saved_models
checkpoints_every_n_epochs: 1
checkpoints_name: null
checkpoints_mode: min
checkpoints_save_top_k: 1
checkpoints_kwargs: {}
load_best: true
track_grad_norm: -1
progress_bar: rich
precision: 32
trainer_kwargs: {}
optimizer: Adam
optimizer_params: {}
lr_scheduler: null
lr_scheduler_params: {}
lr_scheduler_monitor_metric: valid_loss
categorical_dim: 2
continuous_dim: 71
output_dim: 2
output_cardinality:
- 2
categorical_cardinality:
- 34
- 20655
embedded_cat_dim: 67
